### ISSUE TITLE
MVP for soft release

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/gsplot#407]
Trying to describe MVP for soft release.

MVP: scatter plots w/ USGS style 
- USGS theme not tied to session (preloads half-built gsplot object)
- user config

New features: 
- [x] config file method works (#402, #392)
- [x] themes (#385)
- [ ] all gsplot-only features captured in README (config file + themes)
- [x] gsplot object metadata (#304)
- [x] SPN date handling in config (#134)
- [ ] temporarily change pars (#254)
- [ ] global non-pars treated appropriately (#366)
- [x] append axis (#408)

Bugs:
- [x] data.frames can be passed in (#322)
- [ ] formulas can be used (#314)
- [x] dates work (#272, #285)
- [x] index for pts/lines (#245, #224)

Potential power-users to send this to:
- Joe Mills
- Scott Worland

**Comment by lindsayplatt** [comment]
scientific=FALSE as argument to axis for labeling?? #409
